name = "bjj-dagboek"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "bjj-dagboek"
database_id = "b350146c-c19c-428a-a5ba-1587a7f4e20e""
